### ISSUE TITLE
DeprecationWarning while successful execution

### ISSUE THREAD

**Issue by anthonymonori** [drazisil/junit-merge#20]
I'm getting the following deprecation warning:
```
(node:45181) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
I have to say that the output is correct thought and the junit xmls are merged together successfully, buy that warning is still there.

I'm trying to use the latest junit-merge on a MacOS with the following setup:

```
npm -v
5.6.0
node -v
v9.3.0
junit-merge -V
1.2.0
```

Tried running `node --trace-deprecation lib/index.js` on this repo but it came back with nothing.

Any ideas why am I getting this?

**Comment by drazisil** [comment]
I haven't seen that message before. Let me do some digging. Was there more to the output?

**Comment by anthonymonori** [comment]
Unfortunately not. I was wondering if it's my setup (tools versions maybe), but I just installed `junit-merge` on one of my CI servers and the same is outputted. Although those are running on the same versions as I just updated couple of days ago.

I tried looking at help, but could not find any commands to enable more verbose logging.

**Comment by drazisil** [comment]
I think I have it. Should have a fix soon
