### ISSUE TITLE
Error: ReferenceError: merge is not defined since 1.2.2

### ISSUE THREAD

**Issue by GlombSt** [drazisil/junit-merge#27]
We are using this in our CI to merge results.
1.2.2 is broken for us, reverted to 1.2.1 from npm.

<img width="537" alt="grafik" src="https://user-images.githubusercontent.com/5288428/34455957-c619aa3c-ed8a-11e7-971e-ce60dd773ac5.png">

**Comment by drazisil** [comment]
Thanks for the report. Im not at a computer this weekend, but I'll investigate next week.

**Comment by drazisil** [comment]
Thanks for the report. Im not at a computer this weekend, but I'll investigate next week.

**Comment by drazisil** [comment]
@GlombSt  offhand, after a quick glance, i can't see where that error would be coming from. Can you provide what version of NodeJS you are using so i can try to reproduce?

**Comment by drazisil** [comment]
Ah, it's a dependency of jest-jasmine, which is a dev dependency, so not sure why it would be called from the cli. This will have wait until i can get to a computer it seems. 😐

**Comment by drazisil** [comment]
@GlombSt I can't reproduce this. Any additional information you can provide about your setup would be helpful

**Comment by drazisil** [comment]
@GlombSt Found the issue and updated NPM. Thank you again for the report

**Comment by GlombSt** [comment]
Thanks for fixing this Joseph. Would it be cool if you tagged the releases you publish?

**Comment by drazisil** [comment]
@GlombSt On Github? I thought NPM version did that. Yes, let me add that to my flow.
