### ISSUE TITLE
Support for XML without <testsuites> aggregate tag

### ISSUE THREAD

**Issue by peffreycollins** [drazisil/junit-merge#4]
This tool is not merging junit outputs successfully in cases where there is no `<testsuites>` aggregate tag in one of the XML files where there is only one test suite -- which appears to still be valid output according to the spec.

**Comment by drazisil** [comment]
Thanks, will take a look.

**Comment by peffreycollins** [comment]
Thanks!  It works perfectly in all scenarios where both have <testsuites> parent tags.  Unfortunately, karma-junit-reporter doesn't seem to wrap its standalone <testsuite> in the <testsuites> parent tag, and I've been trying to figure out a way to force this in the meantime.

**Comment by drazisil** [comment]
Understood. I should be able to fix this easily, just need to find the time.

**Comment by drazisil** [comment]
@peffreycollins would it be possible for you to provide a (sanitized) example for me to use as test data?

**Comment by peffreycollins** [comment]
Sure thing.  Took this from your example:

```
<?xml version="1.0"?>
    <testsuite name="PhantomJS 1.9.8" package="" timestamp="2016-01-22T18:25:08" id="0" hostname="MacBook-Pro.local" tests="2" errors="0" failures="1" time="0.026">
        <properties>
            <property name="browser.fullName" value="PhantomJS/1.9.8 Safari/534.34"/>
        </properties>
        <testcase name="testcase1.1" time="0.003" classname="PhantomJS 1.9.8.add"/>
        <testcase name="testcase1.2" time="0.001" classname="PhantomJS 1.9.8.FAIL">
            <failure type="">
                AssertionError: expected undefined not to be an undefined
            </failure>
        </testcase>
        <system-out><![CDATA[ foo ]]></system-out>
        <system-err/>
    </testsuite>
```

**Comment by peffreycollins** [comment]
Hey, thanks for the quick fix.  Works like a charm! :)
